language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip uninstall -y overrides
  - pip install overrides==3.1.0
  - pip install git+https://github.com/BatsResearch/labelmodels
  - pip install git+https://github.com/BatsResearch/wiser.git
  - pip install scikit-learn==0.22.2

# command to run tests
script:
  - cd tutorials
  - cd introduction
  - mkdir output
  - cd output
  - mkdir tmp
  - mkdir generative
  - cd generative
  - mkdir link_hmm
  - cd ../
  - mkdir discriminative
  - cd discriminative
  - mkdir link_hmm
  - cd ../../
  - jupyter nbconvert --to script 'Intro Tutorial 1 - Tagging and Linking Rules.ipynb'
  - jupyter nbconvert --to script 'Intro Tutorial 2 - Generative Models.ipynb'
  - jupyter nbconvert --to script 'Intro Tutorial 3 - Neural Networks.ipynb'
  - travis_wait 3000 python 'Intro Tutorial 1 - Tagging and Linking Rules.py'
  - travis_wait 3000 python 'Intro Tutorial 2 - Generative Models.py'
  - travis_wait 3000 python 'Intro Tutorial 3 - Neural Networks.py'
