language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip uninstall -y overrides
  - pip install overrides==3.1.0
  - pip install git+https://github.com/BatsResearch/labelmodels
  - pip install git+https://github.com/BatsResearch/wiser.git
  - pip install scikit-learn==0.22.2
  - cd tutorials
  - cd introduction
  - mkdir output
  - cd output
  - mkdir tmp
  - mkdir generative
  - cd generative
  - mkdir link_hmm
  - cd ../
  - mkdir discriminative
  - cd discriminative
  - mkdir link_hmm
  - cd ../../

script:
  - skip

stages:
  - Notebook 1

jobs:
  include:
    - stage: Notebook 1
    - script: 
      - travis_wait 3000 python ../../test/unit_tests/link_hmm.py