language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip uninstall -y overrides
  - pip install overrides==3.1.0
  - pip install runipy
  - pip install git+https://github.com/BatsResearch/wiser.git

# command to run tests
script:
  - cd tutorials
  - cd introduction
  - mkdir data
  - cd data
  - mkdir tmp
  - cd ../
  - ls
  - mkdir generative
  - cd generative
  - mkdir link_hmm
  - cd ../../
  - ls
  - mkdir discriminative
  - cd discriminative
  - mkdir link_hmm
  - cd ../../../
  - runipy 'Intro Tutorial 1 - Tagging and Linking Rules.ipynb'
  - runipy 'Intro Tutorial 2 - Generative Models.ipynb'
  - runipy 'Intro Tutorial 3 - Neural Networks.ipynb'
