site_name: WISER
site_url: https://github.com/BatsResearch/wiser
nav:
    - Home: index.md
    - About: about.md
    - Tutorial:
        - 'Introduction': tutorial-intro.md 
        - 'Part 1: Tagging and Linking Rules': part-1.md
        - 'Part 2: Generative Models': part-2.md
        - 'Part 3: Neural Networks': part-3.md
theme: readthedocs